---
name: Release

on:
  push:
    branches:    
    - master
  workflow_dispatch:
    inputs:
      git-ref:
        description: The target `git` branch, `git` tag or `git` SHA to be released.
        required: true

jobs:
  release:
    name: Release
    runs-on:
    - self-hosted
    - tools

    steps:
    - name: Check out draino
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.git-ref || 'master' }}
        fetch-depth: 1
    
    - name: Compute image tag from Git SHA
      id: get-tag
      run: |
        tag=$(echo ${{ github.sha }} | cut -c -7)
        echo "::set-output name=tag::$tag"

    - name: Build and push docker image
      uses: actions/build-docker-image@main
      with:
        docker-file-path: Dockerfile
        repository: draino
        push-to-ecr: true
        additional-tags: ${{ steps.get-tag.outputs.tag }}
        aws-accounts: |
          blendregistry

    - name: Install Helm
      uses: actions/setup-helm@main
      with:
        version: v3.4.0
    
    - name: Run chart-releaser
      uses: actions/chart-releaser-action@main
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_SKIP_EXISTING: "true"
      with:
        charts_dir: helm

    - name: Slack notify the user for GitHub Action job failure.
      if: ${{ failure() }}
      uses: actions/slack@main
      with:
        api-key: ${{ secrets.SLACK_ACTION_API_KEY }}
        channel: '@${{ github.actor }}'
        icon-emoji: ':hammer_and_wrench:'
        attachment-text: 'GitHub Action job `${{ github.job }}` failed: https://git.blendlabs.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        attachment-color: danger
