#
# Copyright (c) 2021 - Present. Blend Labs, Inc. All rights reserved
# Blend Confidential - Restricted
#
---
name: InfoSec Anti-Pattern Check

on:
  pull_request:
    branches:
    - master
    - main

jobs:
  semgrep:
    if: ${{ github.base_ref == github.event.repository.default_branch }}

    runs-on:
    - self-hosted
    - sandbox

    steps:
    - name: Checkout repo
      uses: actions/checkout@main

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Run semgrep
      uses: actions/semgrep-scanning@main
